
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mkewllzuprwkyovjtymj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1rZXdsbHp1cHJ3a3lvdmp0eW1qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4NTI2MTQsImV4cCI6MjA2MjQyODYxNH0.MR2MmGROQAw3Ah7RqgxZneCcI_vHs09ZPegLhcoRV1k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Helper function to get public URL for a file in storage
export const getPublicUrl = (bucketName: string, filePath: string) => {
  return `${SUPABASE_URL}/storage/v1/object/public/${bucketName}/${filePath}`;
};
